-- Insert BookitNow.lt grooming providers into PetiFy database
-- This script adds real grooming salons from Lithuania

-- First, let's create some sample users for these providers
-- (In production, these would be real user accounts)

-- Insert users for providers
INSERT INTO AUTH.USERS (
    ID,
    EMAIL,
    ENCRYPTED_PASSWORD,
    EMAIL_CONFIRMED_AT,
    CREATED_AT,
    UPDATED_AT,
    RAW_APP_META_DATA,
    RAW_USER_META_DATA,
    IS_SUPER_ADMIN,
    ROLE,
    AUD,
    INSTANCE_ID
) VALUES (
    'vanilos-user-id',
    'vanilos@example.com',
    CRYPT('password123', GEN_SALT('bf')),
    NOW(),
    NOW(),
    NOW(),
    '{"provider": "email", "providers": ["email"]}',
    '{"name": "Vanilos Salonas"}',
    FALSE,
    'provider',
    'authenticated',
    '00000000-0000-0000-0000-000000000000'
),
(
    'oh-my-dog-user-id',
    'ohmy@example.com',
    CRYPT('password123', GEN_SALT('bf')),
    NOW(),
    NOW(),
    NOW(),
    '{"provider": "email", "providers": ["email"]}',
    '{"name": "OH MY DOG"}',
    FALSE,
    'provider',
    'authenticated',
    '00000000-0000-0000-0000-000000000000'
),
(
    'zoohotel-pavilnys-user-id',
    'zoohotel.pavilnys@example.com',
    CRYPT('password123', GEN_SALT('bf')),
    NOW(),
    NOW(),
    NOW(),
    '{"provider": "email", "providers": ["email"]}',
    '{"name": "Zoohotel Pavilnys"}',
    FALSE,
    'provider',
    'authenticated',
    '00000000-0000-0000-0000-000000000000'
),
(
    'zoohotel-naujoji-user-id',
    'zoohotel.naujoji@example.com',
    CRYPT('password123', GEN_SALT('bf')),
    NOW(),
    NOW(),
    NOW(),
    '{"provider": "email", "providers": ["email"]}',
    '{"name": "Zoohotel Naujoji Vilnia"}',
    FALSE,
    'provider',
    'authenticated',
    '00000000-0000-0000-0000-000000000000'
),
(
    'zoohotel-lazdynai-user-id',
    'zoohotel.lazdynai@example.com',
    CRYPT('password123', GEN_SALT('bf')),
    NOW(),
    NOW(),
    NOW(),
    '{"provider": "email", "providers": ["email"]}',
    '{"name": "Zoohotel Lazdynai"}',
    FALSE,
    'provider',
    'authenticated',
    '00000000-0000-0000-0000-000000000000'
),
(
    'keturkoju-stilius-user-id',
    'keturkoju@example.com',
    CRYPT('password123', GEN_SALT('bf')),
    NOW(),
    NOW(),
    NOW(),
    '{"provider": "email", "providers": ["email"]}',
    '{"name": "Keturkojų Stilius"}',
    FALSE,
    'provider',
    'authenticated',
    '00000000-0000-0000-0000-000000000000'
),
(
    'tauro-grooming-user-id',
    'tauro@example.com',
    CRYPT('password123', GEN_SALT('bf')),
    NOW(),
    NOW(),
    NOW(),
    '{"provider": "email", "providers": ["email"]}',
    '{"name": "Tauro Grooming"}',
    FALSE,
    'provider',
    'authenticated',
    '00000000-0000-0000-0000-000000000000'
) ON CONFLICT (
    ID
) DO NOTHING;

-- Insert providers
INSERT INTO PUBLIC.PROVIDERS (
    ID,
    USER_ID,
    BUSINESS_NAME,
    BUSINESS_TYPE,
    DESCRIPTION,
    LOCATION,
    PRICE_RANGE,
    AVAILABILITY,
    IMAGES,
    CERTIFICATIONS,
    EXPERIENCE_YEARS,
    STATUS,
    CREATED_AT,
    UPDATED_AT
) VALUES (
    'vanilos-salonas-id',
    'vanilos-user-id',
    'Vanilos salonas – gyvūnų kirpykla',
    'grooming',
    'Profesionali gyvūnų kirpykla Kaune. Teikiame aukštos kokybės kirpimo, maudymo ir grožio procedūras jūsų augintiniams.',
    '{"address": "Verkių g. 48B", "city": "Kaunas", "state": "Kauno apskritis", "zip": "LT-09109", "coordinates": {"lat": 54.8985, "lng": 23.9036}}',
    '{"min": 25, "max": 38}',
    '{"monday": [{"start": "09:00", "end": "18:00"}], "tuesday": [{"start": "09:00", "end": "18:00"}], "wednesday": [{"start": "09:00", "end": "18:00"}], "thursday": [{"start": "09:00", "end": "18:00"}], "friday": [{"start": "09:00", "end": "18:00"}], "saturday": [{"start": "10:00", "end": "16:00"}], "sunday": []}',
    '["https://assets.bookitnow.lt/files/uploaded/shops/6dd1eabaee1f421084976000f29bdffe.jpeg"]',
    '["Profesionalus kirpėjas", "Gyvūnų priežiūros sertifikatas"]',
    5,
    'active',
    NOW(),
    NOW()
),
(
    'oh-my-dog-id',
    'oh-my-dog-user-id',
    'OH MY DOG šunų ir kačių kirpykla',
    'grooming',
    'Moderni šunų ir kačių kirpykla Kaune. Teikiame pilną kirpimo, maudymo ir grožio procedūrų spektrą.',
    '{"address": "Kęstučio g. 59", "city": "Kaunas", "state": "Kauno apskritis", "zip": "LT-09109", "coordinates": {"lat": 54.8969, "lng": 23.9047}}',
    '{"min": 40, "max": 60}',
    '{"monday": [{"start": "09:00", "end": "18:00"}], "tuesday": [{"start": "09:00", "end": "18:00"}], "wednesday": [{"start": "09:00", "end": "18:00"}], "thursday": [{"start": "09:00", "end": "18:00"}], "friday": [{"start": "09:00", "end": "18:00"}], "saturday": [{"start": "10:00", "end": "16:00"}], "sunday": []}',
    '["https://assets.bookitnow.lt/files/uploaded/shops/5c3382f35c2c42ac8f0a4ef0d91bc86c.jpeg"]',
    '["Profesionalus kirpėjas", "Gyvūnų priežiūros sertifikatas"]',
    3,
    'active',
    NOW(),
    NOW()
),
(
    'zoohotel-pavilnys-id',
    'zoohotel-pavilnys-user-id',
    'Zoohotel – naminių gyvūnų grožio salonas Pavilnyje',
    'grooming',
    'Profesionalus naminių gyvūnų grožio salonas Vilniuje, Pavilnyje. Teikiame aukštos kokybės kirpimo ir grožio procedūras.',
    '{"address": "Juodasis kl. 31", "city": "Vilnius", "state": "Vilniaus apskritis", "zip": "LT-09109", "coordinates": {"lat": 54.6872, "lng": 25.2797}}',
    '{"min": 35, "max": 45}',
    '{"monday": [{"start": "09:00", "end": "18:00"}], "tuesday": [{"start": "09:00", "end": "18:00"}], "wednesday": [{"start": "09:00", "end": "18:00"}], "thursday": [{"start": "09:00", "end": "18:00"}], "friday": [{"start": "09:00", "end": "18:00"}], "saturday": [{"start": "10:00", "end": "16:00"}], "sunday": []}',
    '["https://assets.bookitnow.lt/files/uploaded/shops/0ac28eadf0934489a12518c5e620066d.jpeg"]',
    '["Profesionalus kirpėjas", "Gyvūnų priežiūros sertifikatas"]',
    4,
    'active',
    NOW(),
    NOW()
),
(
    'zoohotel-naujoji-id',
    'zoohotel-naujoji-user-id',
    'Zoohotel – naminių gyvūnų grožio salonas Naujojoje Vilnioje',
    'grooming',
    'Profesionalus naminių gyvūnų grožio salonas Vilniuje, Naujojoje Vilnioje. Teikiame aukštos kokybės kirpimo ir grožio procedūras.',
    '{"address": "A. Kojelavičiaus g. 168", "city": "Vilnius", "state": "Vilniaus apskritis", "zip": "LT-09109", "coordinates": {"lat": 54.6872, "lng": 25.2797}}',
    '{"min": 35, "max": 45}',
    '{"monday": [{"start": "09:00", "end": "18:00"}], "tuesday": [{"start": "09:00", "end": "18:00"}], "wednesday": [{"start": "09:00", "end": "18:00"}], "thursday": [{"start": "09:00", "end": "18:00"}], "friday": [{"start": "09:00", "end": "18:00"}], "saturday": [{"start": "10:00", "end": "16:00"}], "sunday": []}',
    '["https://assets.bookitnow.lt/files/uploaded/shops/8ad2fb95e9c24fa8929a1690b8e5aab3.jpeg"]',
    '["Profesionalus kirpėjas", "Gyvūnų priežiūros sertifikatas"]',
    4,
    'active',
    NOW(),
    NOW()
),
(
    'zoohotel-lazdynai-id',
    'zoohotel-lazdynai-user-id',
    'Zoohotel – naminių gyvūnų grožio salonas Lazdynuose',
    'grooming',
    'Profesionalus naminių gyvūnų grožio salonas Vilniuje, Lazdynuose. Teikiame aukštos kokybės kirpimo ir grožio procedūras.',
    '{"address": "Architektų g. 70", "city": "Vilnius", "state": "Vilniaus apskritis", "zip": "LT-09109", "coordinates": {"lat": 54.6872, "lng": 25.2797}}',
    '{"min": 35, "max": 45}',
    '{"monday": [{"start": "09:00", "end": "18:00"}], "tuesday": [{"start": "09:00", "end": "18:00"}], "wednesday": [{"start": "09:00", "end": "18:00"}], "thursday": [{"start": "09:00", "end": "18:00"}], "friday": [{"start": "09:00", "end": "18:00"}], "saturday": [{"start": "10:00", "end": "16:00"}], "sunday": []}',
    '["https://assets.bookitnow.lt/files/uploaded/shops/1f8b1bf81b1b4da3a6ebe7d39dd5d862.jpeg"]',
    '["Profesionalus kirpėjas", "Gyvūnų priežiūros sertifikatas"]',
    4,
    'active',
    NOW(),
    NOW()
),
(
    'keturkoju-stilius-id',
    'keturkoju-stilius-user-id',
    'Šunų ir kačių kirpykla „Keturkojų stilius"',
    'grooming',
    'Profesionali šunų ir kačių kirpykla Kėdainiuose. Teikiame aukštos kokybės kirpimo, maudymo ir grožio procedūras.',
    '{"address": "J. Basanavičiaus g. 21", "city": "Kėdainiai", "state": "Kauno apskritis", "zip": "LT-09109", "coordinates": {"lat": 55.2879, "lng": 23.9728}}',
    '{"min": 20, "max": 50}',
    '{"monday": [{"start": "09:00", "end": "18:00"}], "tuesday": [{"start": "09:00", "end": "18:00"}], "wednesday": [{"start": "09:00", "end": "18:00"}], "thursday": [{"start": "09:00", "end": "18:00"}], "friday": [{"start": "09:00", "end": "18:00"}], "saturday": [{"start": "10:00", "end": "16:00"}], "sunday": []}',
    '["https://assets.bookitnow.lt/files/uploaded/shops/e7d4104ad24d470cac2be5ccf9c8b76e.jpeg"]',
    '["Profesionalus kirpėjas", "Gyvūnų priežiūros sertifikatas"]',
    6,
    'active',
    NOW(),
    NOW()
),
(
    'tauro-grooming-id',
    'tauro-grooming-user-id',
    'Tauro Grooming & Skin Care',
    'grooming',
    'Profesionalus gyvūnų kirpimo ir odos priežiūros salonas Vilniuje. Teikiame aukštos kokybės kirpimo, maudymo ir mokymo paslaugas.',
    '{"address": "Verkių g. 27", "city": "Vilnius", "state": "Vilniaus apskritis", "zip": "LT-09109", "coordinates": {"lat": 54.6872, "lng": 25.2797}}',
    '{"min": 70, "max": 70}',
    '{"monday": [{"start": "09:00", "end": "18:00"}], "tuesday": [{"start": "09:00", "end": "18:00"}], "wednesday": [{"start": "09:00", "end": "18:00"}], "thursday": [{"start": "09:00", "end": "18:00"}], "friday": [{"start": "09:00", "end": "18:00"}], "saturday": [{"start": "10:00", "end": "16:00"}], "sunday": []}',
    '["https://assets.bookitnow.lt/files/uploaded/shops/8f7055f146834cf4810b3ca6170e821c.jpeg"]',
    '["Profesionalus kirpėjas", "Gyvūnų priežiūros sertifikatas", "Mokymo sertifikatas"]',
    8,
    'active',
    NOW(),
    NOW()
) ON CONFLICT (
    ID
) DO NOTHING;