-- Create pet ads table for adoption/selling providers
CREATE TABLE PUBLIC.PET_ADS (
    ID UUID DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    PROVIDER_ID UUID REFERENCES PUBLIC.PROVIDERS(ID) ON DELETE CASCADE,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    SPECIES TEXT NOT NULL, -- dog, cat, bird, rabbit, other
    BREED TEXT,
    AGE INTEGER, -- in months
    GENDER TEXT, -- male, female
    SIZE TEXT, -- small, medium, large
    COLOR TEXT,
    WEIGHT DECIMAL(5, 2), -- in kg
    VACCINATION_STATUS TEXT, -- vaccinated, not_vaccinated, unknown
    MEDICAL_NOTES TEXT,
    BEHAVIORAL_NOTES TEXT,
    SPECIAL_NEEDS TEXT[],
    IMAGES TEXT[] DEFAULT '{}',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create pet ad requests table (for customers to request pets)
CREATE TABLE PUBLIC.PET_AD_REQUESTS (
    ID UUID DEFAULT UUID_GENERATE_V4() PRIMARY KEY,
    PET_AD_ID UUID REFERENCES PUBLIC.PET_ADS(ID) ON DELETE CASCADE,
    CUSTOMER_ID UUID REFERENCES PUBLIC.USERS(ID) ON DELETE CASCADE,
    MESSAGE TEXT,
    STATUS TEXT DEFAULT 'pending', -- pending, approved, rejected, completed
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IDX_PET_ADS_PROVIDER ON PUBLIC.PET_ADS (PROVIDER_ID);

CREATE INDEX IDX_PET_ADS_ACTIVE ON PUBLIC.PET_ADS (IS_ACTIVE);

CREATE INDEX IDX_PET_ADS_SPECIES ON PUBLIC.PET_ADS (SPECIES);

CREATE INDEX IDX_PET_AD_REQUESTS_PET_AD ON PUBLIC.PET_AD_REQUESTS (PET_AD_ID);

CREATE INDEX IDX_PET_AD_REQUESTS_CUSTOMER ON PUBLIC.PET_AD_REQUESTS (CUSTOMER_ID);

CREATE INDEX IDX_PET_AD_REQUESTS_STATUS ON PUBLIC.PET_AD_REQUESTS (STATUS);

-- Apply updated_at triggers
CREATE TRIGGER UPDATE_PET_ADS_UPDATED_AT BEFORE
    UPDATE ON PUBLIC.PET_ADS FOR EACH ROW EXECUTE FUNCTION UPDATE_UPDATED_AT_COLUMN();
    CREATE TRIGGER UPDATE_PET_AD_REQUESTS_UPDATED_AT BEFORE
        UPDATE ON PUBLIC.PET_AD_REQUESTS FOR EACH ROW EXECUTE FUNCTION UPDATE_UPDATED_AT_COLUMN();